# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

venmo = Company.create(name: 'Venmo', location: 'San Jose, CA', url:'https://www.google.com/search?rlz=1C1CHBF_enUS891US891&sxsrf=ALeKk00wKoKCEqF4NMJc5HDarJFKgW_hSg:1597333534670&ei=HmA1X960KOu70PEP4NOlqA4&q=jobs+software+engineer&oq=jobs&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgoIABCxAxCDARBDMgUIABCRAjIKCAAQsQMQgwEQQzIFCAAQkQIyCggAELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEM6BAgAEEc6BwgjEOoCECc6BAguECc6CAguELEDEIMBOgQILhBDUPYSWKEYYMUhaAFwA3gAgAF4iAGGBJIBAzIuM5gBAKABAaoBB2d3cy13aXqwAQrAAQE&sclient=psy-ab&ibp=htl;jobs&sa=X&ved=2ahUKEwiY5aXGw5jrAhXTKH0KHafCASAQp4wCMAB6BAgLEAE#fpstate=tldetail&htivrt=jobs&htiq=jobs+software+engineer&htidocid=nMJHekEppVF4EsGLAAAAAA%3D%3D', date_applied: DateTime.now, status: 'Awaiting Response')

ebay = Company.create(name: 'eBay', location: 'San Jose, CA', url: 'https://www.google.com/search?rlz=1C1CHBF_enUS891US891&sxsrf=ALeKk00wKoKCEqF4NMJc5HDarJFKgW_hSg:1597333534670&ei=HmA1X960KOu70PEP4NOlqA4&q=jobs+software+engineer&oq=jobs&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgoIABCxAxCDARBDMgUIABCRAjIKCAAQsQMQgwEQQzIFCAAQkQIyCggAELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEM6BAgAEEc6BwgjEOoCECc6BAguECc6CAguELEDEIMBOgQILhBDUPYSWKEYYMUhaAFwA3gAgAF4iAGGBJIBAzIuM5gBAKABAaoBB2d3cy13aXqwAQrAAQE&sclient=psy-ab&ibp=htl;jobs&sa=X&ved=2ahUKEwiY5aXGw5jrAhXTKH0KHafCASAQp4wCMAB6BAgLEAE#fpstate=tldetail&htivrt=jobs&htiq=jobs+software+engineer&htidocid=fTFMGqAhhasPvnRGAAAAAA%3D%3D', date_applied: 'Wed, 12 Aug 2020 08:53:55 -0700', status: 'Awaiting Response')

stubhub = Company.create(name: 'StubHub', location: 'San Jose, CA', url: 'https://www.google.com/search?rlz=1C1CHBF_enUS891US891&sxsrf=ALeKk00wKoKCEqF4NMJc5HDarJFKgW_hSg:1597333534670&ei=HmA1X960KOu70PEP4NOlqA4&q=jobs+software+engineer&oq=jobs&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgoIABCxAxCDARBDMgUIABCRAjIKCAAQsQMQgwEQQzIFCAAQkQIyCggAELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEM6BAgAEEc6BwgjEOoCECc6BAguECc6CAguELEDEIMBOgQILhBDUPYSWKEYYMUhaAFwA3gAgAF4iAGGBJIBAzIuM5gBAKABAaoBB2d3cy13aXqwAQrAAQE&sclient=psy-ab&ibp=htl;jobs&sa=X&ved=2ahUKEwiY5aXGw5jrAhXTKH0KHafCASAQp4wCMAB6BAgLEAE#fpstate=tldetail&htivrt=jobs&htiq=jobs+software+engineer&htidocid=qzv-Mk4VLgMC4aMGAAAAAA%3D%3D', date_applied: 'Mon, 11 Aug 2020 08:53:55 -0700', status: 'Awaiting Response')

bd = Company.create(name: 'BD', location: 'San Jose, CA', url: 'https://www.google.com/search?rlz=1C1CHBF_enUS891US891&sxsrf=ALeKk00wKoKCEqF4NMJc5HDarJFKgW_hSg:1597333534670&ei=HmA1X960KOu70PEP4NOlqA4&q=jobs+software+engineer&oq=jobs&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgoIABCxAxCDARBDMgUIABCRAjIKCAAQsQMQgwEQQzIFCAAQkQIyCggAELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEM6BAgAEEc6BwgjEOoCECc6BAguECc6CAguELEDEIMBOgQILhBDUPYSWKEYYMUhaAFwA3gAgAF4iAGGBJIBAzIuM5gBAKABAaoBB2d3cy13aXqwAQrAAQE&sclient=psy-ab&ibp=htl;jobs&sa=X&ved=2ahUKEwiY5aXGw5jrAhXTKH0KHafCASAQp4wCMAB6BAgLEAE#fpstate=tldetail&htivrt=jobs&htiq=jobs+software+engineer&htidocid=h9415X-aWlOvXrtmAAAAAA%3D%3D', date_applied: 'Sun, 10 Aug 2020 08:53:55 -0700', status: 'Accepted')

paypal = Company.create(name: 'PayPal', location: 'San Jose, CA', url: 'https://www.google.com/search?rlz=1C1CHBF_enUS891US891&sxsrf=ALeKk00wKoKCEqF4NMJc5HDarJFKgW_hSg:1597333534670&ei=HmA1X960KOu70PEP4NOlqA4&q=jobs+software+engineer&oq=jobs&gs_lcp=CgZwc3ktYWIQAxgAMgQIIxAnMgoIABCxAxCDARBDMgUIABCRAjIKCAAQsQMQgwEQQzIFCAAQkQIyCggAELEDEIMBEEMyBAgAEEMyBwgAELEDEEMyBwgAELEDEEMyBAgAEEM6BAgAEEc6BwgjEOoCECc6BAguECc6CAguELEDEIMBOgQILhBDUPYSWKEYYMUhaAFwA3gAgAF4iAGGBJIBAzIuM5gBAKABAaoBB2d3cy13aXqwAQrAAQE&sclient=psy-ab&ibp=htl;jobs&sa=X&ved=2ahUKEwiY5aXGw5jrAhXTKH0KHafCASAQp4wCMAB6BAgLEAE#fpstate=tldetail&htivrt=jobs&htiq=jobs+software+engineer&htidocid=AXaLI9YKWyLv_bW1AAAAAA%3D%3D', date_applied: 'Sat, 9 Aug 2020 08:53:55 -0700', status: 'Rejected')

venmo_comment_one = Comment.create(content: 'Phone interview scheduled.', company_id: 1)

venmo_comment_two = Comment.create(content: 'In-person interview scheduled.', company_id: 1)
